artifact_location: /Users/nitish_0184/Desktop/Youtube-Comment-Sentiment-Analysis/127.0.0.0/0
creation_time: 1729793975579
experiment_id: '0'
last_update_time: 1729793975579
lifecycle_stage: active
name: Default
