artifact_uri: /Users/nitish_0184/Desktop/Youtube-Comment-Sentiment-Analysis/127.0.0.1/0/0f6a7a342aab45bebe21e88a9b9bb286/artifacts
end_time: 1729794319920
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0f6a7a342aab45bebe21e88a9b9bb286
run_name: luminous-skink-701
run_uuid: 0f6a7a342aab45bebe21e88a9b9bb286
source_name: ''
source_type: 4
source_version: ''
start_time: 1729794319914
status: 3
tags: []
user_id: nitish_0184
