artifact_uri: /Users/nitish_0184/Desktop/Youtube-Comment-Sentiment-Analysis/127.0.0.1/0/c9f4849649584c8a855bdcc908692cda/artifacts
end_time: 1729794268710
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c9f4849649584c8a855bdcc908692cda
run_name: charming-turtle-845
run_uuid: c9f4849649584c8a855bdcc908692cda
source_name: ''
source_type: 4
source_version: ''
start_time: 1729794268704
status: 3
tags: []
user_id: nitish_0184
