artifact_uri: /Users/nitish_0184/Desktop/Youtube-Comment-Sentiment-Analysis/127.0.0.0/0/457b5a3c43a9445eab575f69aedd725b/artifacts
end_time: 1729794149664
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 457b5a3c43a9445eab575f69aedd725b
run_name: grandiose-lamb-291
run_uuid: 457b5a3c43a9445eab575f69aedd725b
source_name: ''
source_type: 4
source_version: ''
start_time: 1729794149658
status: 3
tags: []
user_id: nitish_0184
